### PR TITLE
Enabling automated coverage report to codecov.io

### PR DESCRIPTION
**Pull request by Lucas-C**
The docs also recommend to install the CodeCov GIhHub app, but I do not have the necessary permissions on this repo:
https://docs.codecov.io/docs/quick-start

### CODE REVIEW

**Comment by alexanderankin** [comment]
@Lucas-C you should have admin permissions now

**Comment by alexanderankin** [comment]
@Lucas-C I'll also make you administrator in the organization when you accept.

**Comment by Lucas-C** [comment]
Ok, I confirm I am now admin on this repo.

On this subject @alexanderankin would you also agree to give me the rights on the Pypi `fpdf2` project ?
My username is [LucasC](https://pypi.org/user/LucasC/).

Mergin this now.

**Comment by alexanderankin** [comment]
I've just sent the invite again.

**Comment by Lucas-C** [comment]
Ok, I am admin of the PyFPDF GitHub org. Thank you!

 🎆✨🎇

**Comment by Lucas-C** [comment]
About Pypi, as I asked above, I'd totally understand if you'd prefer to keep the edit rights for yourself.

**Pull request merged**
